# Numpy Arrays

In [1]:
import numpy as np

In [2]:
list=[1,2,3,4,5]

In [3]:
type(list)

list

In [4]:
array=np.array(list)

In [5]:
type(array)

numpy.ndarray

In [6]:
array.shape

(5,)

In [8]:
array.max()

5

In [10]:
array.min()

1

In [11]:
array

array([1, 2, 3, 4, 5])

In [12]:
array[2]

3

In [20]:
list=[[1,2,3],[4,5,6]]

In [21]:
array2d=np.array(list)

In [22]:
type(array2d)

numpy.ndarray

In [23]:
array2d.shape

(2, 3)

In [24]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
array.ndim

1

In [26]:
array2d.ndim

2

In [27]:
array2d.max()

6

In [28]:
array2d.min()

1

In [29]:
list=[[1,2,3],[1,2,3],[1,2,3]]

In [30]:
array3d=np.array(list)

In [31]:
array3d

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [32]:
array3d.shape

(3, 3)

In [33]:
list=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [34]:
array=np.array(list)

In [35]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
array[1]

array([5, 6, 7, 8])

In [40]:
array[1:4]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [42]:
array[2,3]

12

In [46]:
array[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [47]:
array[0:4,1:4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [48]:
array[0:2]=5

In [49]:
array

array([[ 5,  5,  5,  5],
       [ 5,  5,  5,  5],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
zeros=np.zeros(4)

In [51]:
zeros

array([0., 0., 0., 0.])

In [52]:
zeros=np.zeros((2,4))

In [53]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
eye=np.eye(3,4)

In [56]:
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [57]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [59]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [60]:
np.linspace(0,9,2)

array([0., 9.])

In [61]:
np.random.rand(3)

array([0.79433393, 0.26681128, 0.20101153])

In [63]:
np.random.rand(3,2,2)

array([[[0.0184004 , 0.53444178],
        [0.25250968, 0.93545222]],

       [[0.91549349, 0.27612352],
        [0.30078755, 0.03031003]],

       [[0.33340701, 0.77300179],
        [0.59218321, 0.98940633]]])

In [65]:
np.random.randint(5,10)

6

In [69]:
np.random.randint(10,20,10)

array([18, 11, 18, 16, 15, 18, 17, 19, 11, 10])

In [74]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [75]:
array=np.arange(1,10)

In [76]:
array.ndim

1

In [77]:
array.shape

(9,)

In [96]:
array=array.reshape(3,3)

In [97]:
array

array([[0.   , 0.875, 1.75 ],
       [2.625, 3.5  , 4.375],
       [5.25 , 6.125, 7.   ]])

In [82]:
array.shape

(3, 3)

In [101]:
array1=np.arange(9).reshape(3,3)

In [102]:
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [103]:
array2=np.linspace(0,5,9).reshape(3,3)

In [104]:
array2

array([[0.   , 0.625, 1.25 ],
       [1.875, 2.5  , 3.125],
       [3.75 , 4.375, 5.   ]])

In [90]:
p="hi"
q="people"

In [91]:
p+q

'hipeople'

In [105]:
concatenate=np.concatenate((array1,array2),axis=0)

In [106]:
concatenate

array([[0.   , 1.   , 2.   ],
       [3.   , 4.   , 5.   ],
       [6.   , 7.   , 8.   ],
       [0.   , 0.625, 1.25 ],
       [1.875, 2.5  , 3.125],
       [3.75 , 4.375, 5.   ]])

In [107]:
concatenate=np.concatenate((array1,array2),axis=1)

In [108]:
concatenate

array([[0.   , 1.   , 2.   , 0.   , 0.625, 1.25 ],
       [3.   , 4.   , 5.   , 1.875, 2.5  , 3.125],
       [6.   , 7.   , 8.   , 3.75 , 4.375, 5.   ]])

In [110]:
np.delete(concatenate,1,axis=1)

array([[0.   , 2.   , 0.   , 0.625, 1.25 ],
       [3.   , 5.   , 1.875, 2.5  , 3.125],
       [6.   , 8.   , 3.75 , 4.375, 5.   ]])

In [111]:
np.delete(concatenate,[1,2,3],axis=1)

array([[0.   , 0.625, 1.25 ],
       [3.   , 2.5  , 3.125],
       [6.   , 4.375, 5.   ]])

In [114]:
array=np.arange(15)

In [115]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [118]:
ravel=array.ravel()
flatten=array.flatten()

In [119]:
print(ravel)
print(flatten)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [120]:
ravel[6]=22

In [121]:
ravel

array([ 0,  1,  2,  3,  4,  5, 22,  7,  8,  9, 10, 11, 12, 13, 14])

In [122]:
array

array([ 0,  1,  2,  3,  4,  5, 22,  7,  8,  9, 10, 11, 12, 13, 14])

In [125]:
flatten[5]=100

In [126]:
flatten

array([100,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [127]:
array

array([ 0,  1,  2,  3,  4,  5, 22,  7,  8,  9, 10, 11, 12, 13, 14])

In [129]:
array=np.arange(0,9)

In [130]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [132]:
array+array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [133]:
array-array

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [134]:
array*array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [135]:
array/array

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [136]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [137]:
np.exp(array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03])

In [138]:
np.log(array)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154])

In [139]:
np.max(array)

8

In [140]:
np.min(array)

0

In [141]:
np.argmax(array)

8

In [142]:
np.argmin(array)

0